name: Subtree Split for composer packages 

on:
  push:
    tags:
      - 'v*'

jobs:
  sync_commits:
    runs-on: ubuntu-latest
    name: Sync commits
    if: github.repository == 'ueberbit/uebertool' # Execute this workflow job only on the main repository.
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0

      # Add a personal access token to the repository secrets. This will allow the splitter action to push the new commits
      - uses: frankdejonge/use-github-token@1.0.2
        with:
          authentication: 'username:${{ secrets.GITHUB_TOKEN }}'

      # Cache the splitsh executable to speedup future runs
      - name: Cache splitsh-lite
        uses: actions/cache@v2
        with:
          path: './splitsh'
          key: '${{ runner.os }}-splitsh-v101'

      # Sync commits and tags for the configured subtree splits
      - name: subtree split
        uses: acrobat/subtree-splitter@v1.1.3
        with:
          config-path: .github/subtree.json # Reference the location where you saved your config file
