name: Testing

on:
  push:
    branches:
      - main
      - feature/*

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Setup Drupal
        run: composer create-project --no-install --no-interaction drupal/recommended-project:11.1.1 ~/drupal

      - name: Configure composer project
        run: |
          cd ~/drupal
          composer config minimum-stability dev
          composer config prefer-stable true
          composer config repositories.0 '{"type": "path", "url": "'$GITHUB_WORKSPACE'/packages/uebertool-companion", "options": {"symlink": false}}'
          composer require drupal/core-dev:11.1.1
          composer show -a ueberbit/uebertool_companion
     
